name: Packer CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pck.pkr.hcl'

jobs:
  check-packer-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@v1
        with:
          packer-version: '1.7.x' # specify the desired Packer version

      - name: Run 'packer fmt' and check for modifications
        run: |
          packer fmt pck.pkr.hcl
          if [[ $(git status --porcelain) ]]; then
            echo "Packer fmt has made changes to the following files:"
            git --no-pager diff
            exit 1
          fi

      - name: Run 'packer validate'
        run: |
          packer validate pck.pkr.hcl
