name: Build and Distribute AMI

on:
  pull_request:
    branches:
      - main  # Replace with the branch you use, if different

env:
  AWS_REGION: 'us-east-1'  # Update if you're using a different region

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Insert any required setup steps here, such as setting up dependencies required for your build and tests.
      
      - name: Run integration tests
        run: |
          # Add commands to run your integration tests
          # Example: 
          # npm install
          # npm run test

      - name: Build application artifact
        run: |
          # Add commands to build your project's artifact
          # Example:
          # mvn package

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/your/artifact  # Update this path

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Initialize Packer
        run: |
          packer init pck.pkr.hcl  # Ensure this command and file align with your project's specifics

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS CLI version
        run: aws --version

      - name: Build AMI
        run: |
          packer build pck.pkr.hcl  # Ensure this command and file align with your project's specifics

