name: Build and Distribute AMI

on:
  pull_request:
    branches:
      - main  # or replace with the branch you use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Manual installation of Packer
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      # Create webapp.zip from the current repository content
      - name: Download webapp repository
        run: zip -r webapp.zip ./

      # Initialize Packer
      - name: Initialize Packer
        run: |
          packer init pck.pkr.hcl  

      # Configuring AWS credentials for Packer to access AWS
      - name: Configure AWS credentials
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer build pck.pkr.hcl
