name: Node.js Anuja_WorkFlow

on:
   pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Anuja_WorkFlow
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: projectDatabase
          MYSQL_USER: rootuser
          MYSQL_PASSWORD: root1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Wait for MySQL to be ready
      run: |
        while ! nc -z localhost 3306; do
          sleep 1
        done

    - name: Test MySQL Connection
      run: |
        mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "SHOW DATABASES;"

    - name: Create and set up database user
      run: |
        mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "CREATE USER 'rootuser'@'%' IDENTIFIED BY 'root1234';"
        mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "GRANT ALL PRIVILEGES ON *.* TO 'rootuser'@'%';"
        mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "FLUSH PRIVILEGES;"

    - name: Configure database
      run: |
        mysql --host=localhost --port=3306 --user=rootuser --password=root1234 -e "CREATE DATABASE IF NOT EXISTS projectDatabase;"

    - name: Test rootuser Connection
      run: |
        mysql --host=127.0.0.1 --port=3306 --user=rootuser --password=root1234 -e "SHOW DATABASES;"

    - name: List project directory structure
      run: find . -print

    - name: Run Tests
      run: npm test
      env:
        NODE_ENV: "test"
        DB_HOST: "localhost"
        DB_USERNAME: "rootuser"
        DB_PASSWORD: "root1234"
        DB_DATABASE: "projectDatabase"