name: Node.js Anuja_WorkFlow

on:
   pull_request:
    branches:
      - main

jobs:
  build:
    name: Anuja_WorkFlow
    runs-on: ubuntu-latest

    # Add the services section here
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: TestDataBase1
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Display .env file
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=TestDataBase1" >> .env
        echo "PORT=8080" >> .env
        cat .env

    - name: configuremysql
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        # No need to start mysql service manually
        mysql -h 127.0.0.1 -P 3306 -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS TestDataBase1;"

    - name: Run Tests
      run: npm test


 

# checking CI command on PR - 1.2.3
