name: Node.js Anuja_WorkFlow

on:
   pull_request:
    branches:
      - main

jobs:
  build:
    name: Anuja_WorkFlow
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: TestDataBase1
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Wait for MySQL to be ready
      run: |
        while ! nc -z localhost 3306; do
          sleep 1
        done

    - name: Display .env file
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=TestDataBase1" >> .env
        echo "PORT=8080" >> .env
        cat .env

    - name: Set up database user and permissions
      run: |
        mysql --host=localhost --port=3306 --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.DB_USER }}'@'%';"
        mysql --host=localhost --port=3306 --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "FLUSH PRIVILEGES;"

    - name: Configure database
      run: |
        mysql --host=localhost --port=3306 --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS TestDataBase1;"

    - name: Run Tests
      run: npm test
      env:
        NODE_ENV: "test"
        DB_HOST: "localhost"
        DB_USERNAME: "${{ secrets.DB_USER }}"
        DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
        DB_DATABASE: "TestDataBase1"
