name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-packer-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v2

      - name: Manually Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer_1.7.8_linux_amd64.zip
          sudo mv packer /usr/local/bin/
    
      - name: Download webapp repository
        run: zip -r webapp.zip ./

      - name: Run 'packer fmt' and check for modifications
        run: |
          packer fmt pck.pkr.hcl
    
      - name: Initialize Packer
        run: |
          packer init pck.pkr.hcl

      - name: Run 'packer validate'
        run: |
          packer validate pck.pkr.hcl
